function jornada(){var T='',Bb='" for "gwt:onLoadErrorFn"',zb='" for "gwt:onPropertyErrorFn"',mb='"><\/script>',bb='#',Jb='&',Sb='.cache.html',db='/',pb='//',Rb=':',tb='::',_b='<script defer="defer">jornada.onInjectionDone(\'jornada\')<\/script>',lb='<script id="',wb='=',cb='?',yb='Bad handler "',$b='DOMContentLoaded',Qb="GWT module 'jornada' may need to be (re)compiled",nb='SCRIPT',Mb='Unexpected exception in locale detection, using default: ',Kb='_',Lb='__gwt_Locale',kb='__gwt_marker_jornada',ob='base',gb='baseUrl',X='begin',W='bootstrap',fb='clear.cache.gif',vb='content',Hb='default',ab='end',Zb='gwt-cal-google.css',Y='gwt.codesvr=',Z='gwt.hosted=',$='gwt.hybrid',Tb='gwt/clean/clean.css',Ab='gwt:onLoadErrorFn',xb='gwt:onPropertyErrorFn',ub='gwt:property',Yb='head',Ob='hosted.html?jornada',Xb='href',Cb='iframe',eb='img',Db="javascript:''",U='jornada',ib='jornada.nocache.js',sb='jornada::',Ub='link',Nb='loadExternalRefs',Gb='locale',Ib='locale=',qb='meta',Fb='moduleRequested',_='moduleStartup',rb='name',Eb='position:absolute;width:0;height:0;border:none',Vb='rel',hb='script',Pb='selectingPermutation',V='startup',Wb='stylesheet',jb='undefined';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=T,u={},v=[],w=[],A=[],B=0,C,D;o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:W,millis:(new Date).getTime(),type:X});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function F(){var b=false;try{var c=m.location.search;return (c.indexOf(Y)!=-1||(c.indexOf(Z)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf($)==-1}catch(a){}F=function(){return b};return b}
function G(){if(q&&r){var b=n.getElementById(U);var c=b.contentWindow;if(F()){c.__gwt_getProperty=function(a){return L(a)}}jornada=null;c.gwtOnLoad(C,U,t,B);o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:_,millis:(new Date).getTime(),type:ab})}}
function H(){function e(a){var b=a.lastIndexOf(bb);if(b==-1){b=a.length}var c=a.indexOf(cb);if(c==-1){c=a.length}var d=a.lastIndexOf(db,Math.min(c,b));return d>=0?a.substring(0,d+1):T}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(eb);b.src=a+fb;a=e(b.src)}return a}
function g(){var a=K(gb);if(a!=null){return a}return T}
function h(){var a=n.getElementsByTagName(hb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(ib)!=-1){return e(a[b].src)}}return T}
function i(){var a;if(typeof isBodyLoaded==jb||!isBodyLoaded()){var b=kb;var c;n.write(lb+b+mb);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=nb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return T}
function j(){var a=n.getElementsByTagName(ob);if(a.length>0){return a[a.length-1].href}return T}
function k(){var a=n.location;return a.href==a.protocol+pb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==T){l=h()}if(l==T){l=i()}if(l==T){l=j()}if(l==T&&k()){l=e(n.location.href)}l=f(l);t=l;return l}
function I(){var b=document.getElementsByTagName(qb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(rb),g;if(f){f=f.replace(sb,T);if(f.indexOf(tb)>=0){continue}if(f==ub){g=e.getAttribute(vb);if(g){var h,i=g.indexOf(wb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=T}u[f]=h}}else if(f==xb){g=e.getAttribute(vb);if(g){try{D=eval(g)}catch(a){alert(yb+g+zb)}}}else if(f==Ab){g=e.getAttribute(vb);if(g){try{C=eval(g)}catch(a){alert(yb+g+Bb)}}}}}}
function J(a,b){return b in v[a]}
function K(a){var b=u[a];return b==null?null:b}
function L(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(D){D(a,d,b)}throw null}
var M;function N(){if(!M){M=true;var a=n.createElement(Cb);a.src=Db;a.id=U;a.style.cssText=Eb;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:_,millis:(new Date).getTime(),type:Fb});a.contentWindow.location.replace(t+P)}}
w[Gb]=function(){var b=null;var c=Hb;try{if(!b){var d=location.search;var e=d.indexOf(Ib);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Jb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=K(Gb)}if(!b){var h=navigator.browserLanguage?navigator.browserLanguage:navigator.language;if(h){var i=h.split(/[-_]/);if(i.length>1){i[1]=i[1].toUpperCase()}b=i.join(Kb)}}if(!b){b=m[Lb]}if(b){c=b}while(b&&!J(Gb,b)){var j=b.lastIndexOf(Kb);if(j<0){b=null;break}b=b.substring(0,j)}}catch(a){alert(Mb+a)}m[Lb]=c;return b||Hb};v[Gb]={ar:0,bg:1,cs:2,da:3,de:4,'default':5,en:6,es:7,es_MX:8,fi:9,fr:10,hu:11,it:12,ja:13,ko:14,nl:15,nn_NO:16,no:17,pl:18,pl_PL:19,pt_BR:20,ru:21,sk:22,sl:23,sv:24,sv_SE:25,tr:26,zh_CN:27,zh_TW:28};jornada.onScriptLoad=function(){if(M){r=true;G()}};jornada.onInjectionDone=function(){q=true;o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:Nb,millis:(new Date).getTime(),type:ab});G()};I();H();var O;var P;if(F()){if(m.external&&(m.external.initModule&&m.external.initModule(U))){m.location.reload();return}P=Ob;O=T}o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:W,millis:(new Date).getTime(),type:Pb});if(!F()){try{alert(Qb);return;var Q=O.indexOf(Rb);if(Q!=-1){B=Number(O.substring(Q+1));O=O.substring(0,Q)}P=O+Sb}catch(a){return}}var R;function S(){if(!s){s=true;if(!__gwt_stylesLoaded[Tb]){var a=n.createElement(Ub);__gwt_stylesLoaded[Tb]=a;a.setAttribute(Vb,Wb);a.setAttribute(Xb,t+Tb);n.getElementsByTagName(Yb)[0].appendChild(a)}if(!__gwt_stylesLoaded[Zb]){var a=n.createElement(Ub);__gwt_stylesLoaded[Zb]=a;a.setAttribute(Vb,Wb);a.setAttribute(Xb,t+Zb);n.getElementsByTagName(Yb)[0].appendChild(a)}G();if(n.removeEventListener){n.removeEventListener($b,S,false)}if(R){clearInterval(R)}}}
if(n.addEventListener){n.addEventListener($b,function(){N();S()},false)}var R=setInterval(function(){if(/loaded|complete/.test(n.readyState)){N();S()}},50);o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:W,millis:(new Date).getTime(),type:ab});o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:Nb,millis:(new Date).getTime(),type:X});n.write(_b)}
jornada();